### ISSUE TITLE
Cannot use buildpack 

### ISSUE THREAD

**Issue by halcwb** [SuaveIO/mono-script-buildpack#9] opened 2016-06-15 15:16 UTC
For a couple of days this buildpack cannot be used because of:

> Download and import trusted root certificates from Mozilla's MXR.
> Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.
> Downloading from 'http://mxr.mozilla.org/seamonkey/source/security/nss/lib/ckfw/builtins/certdata.txt?raw=1'...
> Couldn't retrieve the file using the supplied information.
>  !     Push rejected, failed to compile SuaveFramework app

When you go to the certificate download site, indeed, it reads out of order. But in the meanwhile, you cannot deploy to heroku either.

**Comment by haf** [comment] 2016-06-15 15:43
I think the new repos by Xamarin contain the certificates listing, too, actually... Could you verify? In that case we can remove this line.

**Comment by halcwb** [comment] 2016-06-15 16:35
I have not a lot of know how in this area, but I don't think that it is required anymore with the new versions:

> Mono on Linux before 3.12 by default didn’t trust any SSL certificates so you got errors when accessing HTTPS resources. This is not required anymore as 3.12 and later include a new tool that runs on package installation and syncs Mono’s certificate store with the system certificate store (on older versions you had to import Mozilla’s list of trusted certificates by running mozroots --import --sync). Some systems are configured in a way so that the necessary package isn’t pulled in when Mono is installed, in those cases make sure the ca-certificates-mono package is installed.

**Comment by haf** [comment] 2016-06-15 18:01
@halcwb Could you PR the removal of the line and make that your first contribution in a string of hopefully many more ;)?

**Comment by halcwb** [comment] 2016-06-15 20:03
I am afraid its not working, and this is not really my cup of thee. I have been looking at: https://github.com/adamburgess/heroku-buildpack-mono.

**Comment by halcwb** [comment] 2016-06-17 00:20
Unfortunately, the mono build pack (any others as well) is still broken due to this problem:

> -----> Importing trusted root certificates
> Mozilla Roots Importer - version 3.12.1.0
> Download and import trusted root certificates from Mozilla's MXR.
> Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.
> Downloading from 'http://mxr.mozilla.org/seamonkey/source/security/nss/lib/ckfw/builtins/certdata.txt?raw=1'...
> Couldn't retrieve the file using the supplied information.
>  !     Push rejected, failed to compile SuaveFramework app

The site for the certificates is down. But just omitting the download doesn't work either, because then paket cannot download the packages. I also tried newer mono versions, but still the same problem.

**Comment by haf** [comment] 2016-06-17 07:55
Ping @directhex – what should we do?

**Comment by edmorley** [comment] 2016-06-17 11:47
Mozilla's MXR site is likely not coming back (see https://bugzilla.mozilla.org/show_bug.cgi?id=1279952).

It's worth noting that the URL:
- was to Mozilla's code indexer, which is not intended for direct use (a source repo is a more appropriate choice than a code indexer)
- used HTTP (!!) which is pretty bad given the nature of the file
- was from an ancient version of the file (that seamonkey repo hasn't been updated for years)

The same suffix list is now made available via it's own site, see:
https://publicsuffix.org/list/

**Comment by directhex** [comment] 2016-06-17 12:35
@haf either submit a fix to mozroots (and possibly carry a patch downstream until that fix lands in a stable release), or switch to using cert-sync from a directory on disk containing a trusted set of certs.

Or both!

It's hardly an insurmountable fix - https://github.com/mono/mono/blob/master/mcs/tools/security/mozroots.cs#L47 for the former, https://github.com/mono/linux-packaging-mono/blob/centos/mono-core.spec#L381-L382 for the latter

**Comment by akoeplinger** [comment] 2016-06-20 14:54
Hey, I've opened https://github.com/mono/mono/pull/3188 to move away from the MXR url in mozroots. You can do the same as a workaround for now by passing `--url http://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt` to mozroots.

Please note that we strongly encourage everyone to move to cert-sync on Mono >= 3.12.

@edmorley publicsuffix.org is not a replacement since they don't distribute the CA certs there.

**Comment by edmorley** [comment] 2016-06-20 15:03
> @edmorley publicsuffix.org is not a replacement since they don't distribute the CA certs there.

Sorry there are people using both effective_tld_names.dat and certdata.txt from MXR, the last sentence of the above comment was aimed at people using the former - must have mixed up my tabs.

> You can do the same as a workaround for now by passing --url http://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt to mozroots.

Please don't use HTTP urls - hg.m.o is available over HTTPS too. (Arguably we should redirect and set HTTPS, but there are a few blockers remaining - https://bugzilla.mozilla.org/show_bug.cgi?id=450645)

**Comment by akoeplinger** [comment] 2016-06-20 15:12
@edmorley unfortunately as I mentioned in the PR we can't use HTTPS in mozroots, because the whole purpose of mozroots is fetching CA certificates when the system has none already. Moving/redirecting to HTTPS would break us there as well.

If the plan is to make hg.m.o only available over HTTPS then I'll need to reconsider my fix.

**Comment by edmorley** [comment] 2016-06-20 15:24
Oh my apologies, I was thinking this was just to update or supplement the system certs rather than bootstrap them completely. To be honest for that reason + general reliability, I'd recommend not pulling them in directly, but having a checked-in copy, which is updated periodically using an in-repo sync script, that is run from a system that does have CA certs set up.

**Comment by akoeplinger** [comment] 2016-06-20 15:42
Yeah, mozroots is deprecated since the Mono 3.12 (~1.5 years) release anyway but there are unfortunately still users using it...

**Comment by akoeplinger** [comment] 2016-06-21 15:28
@edmorley I've updated the https://github.com/mono/mono/pull/3188 to fetch from the HTTPS hg URL and simply ignore cert errors and print a warning. I think this is the best we can do to unbreak people.

**Comment by haf** [comment] 2016-06-21 16:23
@akoeplinger Why not take his advice and do a script that periodically updates it?

**Comment by akoeplinger** [comment] 2016-06-21 16:24
@haf periodically update it where? you mean shipping the cert list with Mono?

**Comment by haf** [comment] 2016-06-21 18:47
As a package with mono yes. Surely you'd recognise that turning of HTTPS validation or even initially loading the list over plaintext without any authentication, verification what so ever is not the best way to go about?

**Comment by akoeplinger** [comment] 2016-06-21 18:57
@haf that would put the burden of keeping those certificates up to date on us, which we obviously don't want.

There's no reason to still use mozroots if you're using Mono >= 3.12 (or OSX) as cert-sync is a much better solution (and runs automatically on package installation) so investing time into mozroots doesn't make sense to me. And yeah, I agree that fetching the list over http or https-without-verification is less than ideal.

**Comment by haf** [comment] 2016-06-21 19:31
It's not just less than ideal, it's, well... At least worthy of a gif. I hope you see my point?

You don't need to have much more of a burden than running a script every month and inspect the list, right?

**Comment by akoeplinger** [comment] 2016-06-21 19:35
@haf it's been that way since the mozroots tool was introduced - over 10 years now. I don't really see your point of why we should do the work of introducing a system for fetching/packaging/distributing this list **now** when we clearly want everyone to move away from mozroots.

Is there a reason why you want to stick with mozroots?

Oh and btw. you can still fetch the certdata.txt file via wget/curl from the https URL and pass it to the `--file` parameter of mozroots.

**Comment by haf** [comment] 2016-06-22 21:23
@akoeplinger I must be misunderstanding; are you moving to using the OS dist's certs rather than scaffolding your own then?

**Comment by akoeplinger** [comment] 2016-06-22 22:29
@haf yes, we did in Mono 3.12. The `ca-certificates-mono` package provides cert-sync and uses it to synchronize the Linux CA certs into the Mono trust store (it also has hooks so whenever the OS certs are updated it runs again). Note that on OSX we've always been using the OS certs.

More details about cert-sync: http://www.mono-project.com/docs/about-mono/releases/3.12.0/#cert-sync

**Comment by drusellers** [comment] 2016-08-17 23:14
This just bite me today. @haf what can I do to help? I was hoping to deploy some Suave to Heroku

**Comment by haf** [comment] 2016-08-18 07:01
You could upgrade Mono in the buildpack and validate that it works 
through reading this issue and following the instructions, if you would 
like to. Any help would be much appreciated.

**Comment by drusellers** [comment] 2016-08-18 12:29
Any reason not to upgrade to `4.4 SR1 (4.4.2.11)`

**Comment by drusellers** [comment] 2016-08-18 12:35
FYI: It looks like the `mono-builder` repo is behind by one commit from https://github.com/friism/mono-builder which is running mono 4.0.1.  Thoughts on just pulling that in?

**Comment by haf** [comment] 2016-08-18 19:02
No reason at all; go ahead and PR it.

**Comment by drusellers** [comment] 2016-08-18 22:07
challenge accepted https://github.com/SuaveIO/mono-builder/pull/1

**Comment by drusellers** [comment] 2016-08-18 22:07
Once this mono-builder is successfully merged in, we should then be able to upgrade this repo to use the new slug, and hopefully close the issue out. :)

**Comment by ghost** [comment] 2016-10-05 10:36
What is the status of this issue? I can see the that the change mentioned by @drusellers is merged in on 21 August (https://github.com/SuaveIO/mono-script-buildpack/commit/9a3fa859565cfadfb0b9056ee291cd4501ffb25a), but the issue is still open and I also still get an SSL error when using this build pack to deploy to Heroku
(System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server. Error code: 0xffffffff800b010a).

**Comment by haf** [comment] 2016-10-05 10:50
Well it was merged. SSL certs change though. Perhaps you could start a new issue for your problem? We aim to have it all working at all times, but we're dependent on benefactors like yourself to contribute fixes. So please start a new issue and we'll close down this old one with a merged PR.

**Closed as completed** 2016-10-05 10:50 UTC
