### ISSUE TITLE
Failed to download and import trusted root certificates from Mozilla's MXR.

### ISSUE THREAD

**Issue by adicirstei** [SuaveIO/mono-script-buildpack#10] opened 2016-07-20 10:32 UTC
Hi,

I recently tried to use the buildpack and it fails at some point while pushing to heroku. Any idea?

Here is the error:

```
λ git push heroku master
Counting objects: 55, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (46/46), done.
Writing objects: 100% (55/55), 4.38 MiB | 119.00 KiB/s, done.
Total 55 (delta 6), reused 5 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Fetching set buildpack https://github.com/SuaveIO/mono-script-buildpack.git... done
remote: -----> SuaveFramework app detected
remote: -----> Downloading mono to /app/tmp/cache/cedar-14/vendor
remote:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
remote:                                  Dload  Upload   Total   Spent    Left  Speed
remote: 100   154  100   154    0     0   1321      0 --:--:-- --:--:-- --:--:--  1327
remote: 100   158  100   158    0     0    576      0 --:--:-- --:--:-- --:--:--   576
remote: 100 1647k  100 1647k    0     0  3731k      0 --:--:-- --:--:-- --:--:-- 59.5M
remote:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
remote:                                  Dload  Upload   Total   Spent    Left  Speed
remote: 100   586    0   586    0     0   9379      0 --:--:-- --:--:-- --:--:--  9451
remote: 100 4443k  100 4443k    0     0  16.6M      0 --:--:-- --:--:-- --:--:-- 16.6M
remote: -----> Copying /app/tmp/cache/cedar-14/vendor/mono to /tmp/build_e249cdea7e244146e5e95f2a81166585/vendor
remote: -----> Linking /tmp/build_e249cdea7e244146e5e95f2a81166585/vendor/mono --> /app
remote: -----> Setting envvars
remote: -----> Importing trusted root certificates
remote: Mozilla Roots Importer - version 3.12.1.0
remote: Download and import trusted root certificates from Mozilla's MXR.
remote: Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.
remote:
remote: Downloading from 'http://mxr.mozilla.org/seamonkey/source/security/nss/lib/ckfw/builtins/certdata.txt?raw=1'...
remote: Couldn't retrieve the file using the supplied information.
remote:
remote:  !     Push rejected, failed to compile SuaveFramework app
remote:
remote: Verifying deploy...
remote:
remote: !       Push rejected to sv-bookmarks.
```

**Comment by haf** [comment] 2016-07-20 12:20
Yes, this is a duplicate of #9 but even though we've solved the issue, noone has submitted a PR with the fix yet.

**Closed as completed by haf** 2016-07-20 12:20 UTC
